### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

### ISSUE THREAD

**Issue by Entretoize** [Mukosame/Zooming-Slow-Mo-CVPR-2020#48]
I'm trying to install, but receive the following error:

```
# bash make.sh
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 42, in get_extensions
    raise NotImplementedError('Cuda is not availabel')
NotImplementedError: Cuda is not availabel
```

I added that in make.sh:
```
export CUDA_HOME=/usr/local/cuda-11.0
export CUDNN_INCLUDE_DIR=/usr/local/cuda-11.0/include
export CUDNN_LIB_DIR=/usr/local/cuda-11.0/lib64
```

But that just changed the error to:
`No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.0'`

This is  torch.cuda.is_available() that returns false.

**Comment by wen-coder** [comment]
版本对应问题的可以注意一下
