### ISSUE TITLE
Out Of Memory

### ISSUE THREAD

**Issue by erdog** [Mukosame/Zooming-Slow-Mo-CVPR-2020#8]
Running zsm_my_video.sh. No matter what I do, I keep getting out of memory errors. I'm using an RTX 2060 with 16GB of system RAM and 6GB of dedicated GPU RAM. I'm running against a 1 second clip from a 480p video.

RuntimeError: CUDA out of memory. Tried to allocate 676.00 MiB (GPU 0; 6.00 GiB total capacity; 3.49 GiB already allocated; 662.13 MiB free; 3.66 GiB reserved in total by PyTorch) (malloc at ..\c10\cuda\CUDACachingAllocator.cpp:289)

**Comment by erdog** [comment]
Full stack trace

`Traceback (most recent call last):
  File "video_to_zsm.py", line 131, in <module>
    main()
  File "video_to_zsm.py", line 110, in main
    output = single_forward(model, imgs_in)
  File "video_to_zsm.py", line 89, in single_forward
    model_output = model(imgs_temp)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\anon\Documents\Zooming-Slow-Mo-CVPR-2020\codes\models\modules\Sakuya_arch.py", line 336, in forward
    feats = self.ConvBLSTM(lstm_feats)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\anon\Documents\Zooming-Slow-Mo-CVPR-2020\codes\models\modules\Sakuya_arch.py", line 252, in forward
    out_fwd, _ = self.forward_net(x)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\anon\Documents\Zooming-Slow-Mo-CVPR-2020\codes\models\modules\Sakuya_arch.py", line 219, in forward
    h_temp = self.pcd_h(in_tensor, h)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\anon\Documents\Zooming-Slow-Mo-CVPR-2020\codes\models\modules\Sakuya_arch.py", line 157, in forward
    aligned_fea = self.pcd_align(fea1, fea2)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\anon\Documents\Zooming-Slow-Mo-CVPR-2020\codes\models\modules\Sakuya_arch.py", line 91, in forward
    L1_fea = self.L1_dcnpack_1(fea1[0], L1_offset)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\anon\Documents\Zooming-Slow-Mo-CVPR-2020\codes\models\modules\DCNv2\dcn_v2.py", line 140, in forward
    self.dilation, self.deformable_groups)
  File "C:\Users\anon\Documents\Zooming-Slow-Mo-CVPR-2020\codes\models\modules\DCNv2\dcn_v2.py", line 27, in forward
    ctx.dilation[1], ctx.deformable_groups)
RuntimeError: CUDA out of memory. Tried to allocate 676.00 MiB (GPU 0; 6.00 GiB total capacity; 3.49 GiB already allocated; 662.13 MiB free; 3.66 GiB reserved in total by PyTorch) (malloc at ..\c10\cuda\CUDACachingAllocator.cpp:289)
(no backtrace available)`

**Comment by Mukosame** [comment]
Hi, you can edit zsm_my_video.sh and set "--N_out 7" to smaller numbers, like 3 or 5

**Comment by erdog** [comment]
Thanks for fast response. I did try that. I tried 3 and 5, same issue. What is the variable N_in used for? It doesnt appear to be used.

**Comment by erdog** [comment]
Using --N_out 3:

`Traceback (most recent call last):
  File "video_to_zsm.py", line 131, in <module>
    main()
  File "video_to_zsm.py", line 110, in main
    output = single_forward(model, imgs_in)
  File "video_to_zsm.py", line 89, in single_forward
    model_output = model(imgs_temp)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\anon\Documents\Zooming-Slow-Mo-CVPR-2020\codes\models\modules\Sakuya_arch.py", line 342, in forward
    out = self.lrelu(self.pixel_shuffle(self.upconv2(out)))
  File "C:\Users\anon\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 3.52 GiB (GPU 0; 6.00 GiB total capacity; 1.98 GiB already allocated; 1.70 GiB free; 2.60 GiB reserved in total by PyTorch)`

**Comment by Mukosame** [comment]
Hi, please check this loc: https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/master/codes/video_to_zsm.py#L23
I guess you need to try a smaller size of video for now. I'll try to solve it in the following updates.

**Comment by erdog** [comment]
Thanks. I'll try that.

**Comment by erdog** [comment]
Commenting out line `out = self.lrelu(self.pixel_shuffle(self.upconv2(out)))` in Sakuya_arch.py, and using N_out=3 allows a few new frames to be created before running out of memory.

**Comment by Mukosame** [comment]
Thanks for bringing this up. I think this can be fixed after I optimizing the workflow of test.py. I'll let you know as soon as I fix it!

**Comment by phexic** [comment]
Same proble, look forward to updates

**Comment by phexic** [comment]
Runing test.py, always encounter out of memory, I'm using an tesla with 16GB GPU RAM
Traceback (most recent call last):
  File "test.py", line 225, in <module>
    main()
  File "test.py", line 91, in main
    model = model.to(device)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: out of memory

**Comment by pockybyjade** [comment]
Hi, I Commented out line `out = self.lrelu(self.pixel_shuffle(self.upconv2(out))）` in Sakuya_arch.py.although no error will be reported, the output video and pictures will all turn blue, so I do not recommend this.

**Comment by Namnodorel** [comment]
I have the same issue. I messed around a bit with `zsm_my_video.py` to make it load smaller batches of images into RAM at a time, but it still quickly runs out of dedicated GPU RAM. 
My test video had a resolution of 432x236, but I have only 4GB dedicated and 16GB "normal" RAM available.

**Comment by NJ2020** [comment]
Hi,
I am running video_to_zsm.py on a system with 2080Ti GPU (11GB) and 32 GB of system RAM on 1 second clip of 480p video. OS is Ubuntu 18.04 LTS. I have set also set N_out = 1.

It is running out of system RAM consuming all 32 GB and finally killing the process.  Could you please suggest any work around/solution for this?

**Comment by JadeWu233** [comment]
Hi，
First, you can't set N_out to 1, because N_out refers to the number of output frames. The N parameter author has said that it can only be set to 3, 5, 7.&nbsp;&nbsp;I recommended you take a closer look at the code to understand what N_out stands for. Maybe you can try to set N_out&nbsp; to 3, or lower your input video resolution.
Listening to your description seems to be running on the CPU, which is obviously not correct, you should run on the GPU.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"NJ"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 晚上11:41
收件人:&nbsp;"Mukosame/Zooming-Slow-Mo-CVPR-2020"<Zooming-Slow-Mo-CVPR-2020@noreply.github.com&gt;;
抄送:&nbsp;"Jade"<496582128@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Mukosame/Zooming-Slow-Mo-CVPR-2020] Out Of Memory (#8)





 
Hi,
 I am running video_to_zsm.py on a system with 2080Ti GPU (11GB) and 32 GB of system RAM on 1 second clip of 480p video. OS is Ubuntu 18.04 LTS. I have set also set N_out = 1.
 
It is running out of system RAM consuming all 32 GB and finally killing the process.  Could you please suggest any work around/solution for this?

**Comment by NJ2020** [comment]
Hi Jade,

Thanks for the response. Yes, the issue disappears once N_out is set to 3
and I am able to run it successfully.

Thanks & Best Regards,
NJ

**Comment by jiqirenno1** [comment]
Encounter the same problem，

```
Traceback (most recent call last):
  File "./video_to_zsm.py", line 126, in <module>
    main()
  File "./video_to_zsm.py", line 105, in main
    output = single_forward(model, imgs_in)
  File "./video_to_zsm.py", line 86, in single_forward
    model_output = model(imgs_temp)
  File "/home/ubuntu/miniconda3/envs/my/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/ubuntu/6d2d0331-b42f-419a-b343-592105134c85/ubuntu/data/Prjpython/Zooming-Slow-Mo-CVPR-2020/codes/models/modules/Sakuya_arch.py", line 342, in forward
    out = self.lrelu(self.pixel_shuffle(self.upconv2(out)))
  File "/home/ubuntu/miniconda3/envs/my/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/miniconda3/envs/my/lib/python3.7/site-packages/torch/nn/modules/pixelshuffle.py", line 43, in forward
    return F.pixel_shuffle(input, self.upscale_factor)
RuntimeError: CUDA out of memory. Tried to allocate 2.64 GiB (GPU 0; 7.93 GiB total capacity; 4.13 GiB already allocated; 1.08 GiB free; 6.35 GiB reserved in total by PyTorch)
```

**Comment by Mukosame** [comment]
The newest version should consume less memory and the CUDA memory.
